name: JVM Flags

on: 
  push:
  pull_request:

jobs:

  flag_1:
    runs-on: ubuntu-latest
    steps:
      # clones the repo at job start
      - uses: actions/checkout@v3    
      # set-up Java 22 for build
      - uses: actions/setup-java@v3    
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: test flag 1
      # `|` sequentially runs commands on multiple lines
      # `echo` prints
      # `export` makes `MAVEN_OPTS` available to `clean` & `verify`
      # `MAVEN_OPTS = JVM flag` sets the flag for each job
      # `clean` removes previously compiled files
      # `verify` checks build is correct
        run: |                         
          echo 'JVM Flag 1: -XX:+UseCompressedOops'
          echo 'Randomly choosen from the server side article'
          export MAVEN_OPTS='-XX:+UseCompressedOops'
          mvn clean verify
          
  flag_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3                                         
      - uses: actions/setup-java@v3                                       
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: test flag 2
        run: |                         
          echo 'JVM Flag 2: -XX:+UseZGC'
          echo 'Randomly choosen from the server side article'
          export MAVEN_OPTS='-XX:+UseZGC'
          mvn clean verify
    
  flag_3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3                                         
      - uses: actions/setup-java@v3                                       
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: test flag 3
        run: |                         
          echo 'JVM Flag 3: -Xmx2048'
          echo 'Randomly choosen from the server side article'
          export MAVEN_OPTS='-Xmx2048'
          mvn clean verify
    
  flag_4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3                                         
      - uses: actions/setup-java@v3                                       
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: test flag 4
        run: |                         
          echo 'JVM Flag 4: -XX:+UseParNewGC'
          echo 'Randomly choosen from the server side article'
          export MAVEN_OPTS='-XX:+UseParNewGC'
          mvn clean verify
    
  flag_5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3                                         
      - uses: actions/setup-java@v3                                       
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: test flag 5
        run: |                         
          echo 'JVM Flag 5: -XX:MaxPermSize=128m'
          echo 'Randomly choosen from the server side article'
          export MAVEN_OPTS='-XX:MaxPermSize=128m'
          mvn clean verify
